services:
  - type: worker
    name: discord-bot
    env: node
    buildCommand: "npm install"
    startCommand: "node Index.js"
    autoDeploy: true
    envVars:
      - key: DISCORD_BOT_TOKEN
        fromSecret: DISCORD_BOT_TOKEN
