services:
  - type: worker
    name: discord-bot
    env: node
    buildCommand: "npm install"
    startCommand: "node index.js"
    autoDeploy: true
    envVars:
      TOKEN: 
        fromSecret: DISCORD_BOT_TOKEN
